name: Apollo graphql
rating: 5
imageUrl: https://github.com/msa-ez/template-axon2/assets/130956306/316f539b-f474-4135-9785-3d2cb821e132
templateName: apollo-graphql
description: Apollo graphql description
