name: Apollo graphql
rating: 5
imageUrl: https://github.com/msa-ez/template-eventuate/assets/123912988/82c6d95d-ad47-4b4b-9599-41a97b599efc
templateName: apollo-graphql
description: Apollo graphql description
